Nakamoto test
dejiren-training/test pull request #2
Opened 2024-07-10 08:26 UTC by itsuki-jp

test

2024-07-10 08:27 UTC, itsuki-jp commented
コメント

2024-07-10 08:29 UTC, itsuki-jp commented
コメントが見たいな

2024-07-11 02:00 UTC, itsuki-jp commented
あささｓ

2024-07-11 03:55 UTC, yuu104 requested changes

2024-07-11 03:55 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
7行は多いな
3行にしようか

2024-07-11 04:04 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
へろへろ

2024-07-11 04:04 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
はろはろ

2024-07-11 04:07 UTC, itsuki-jp commented on oyoyo.txt
> +oyoyo
はろはろ

2024-07-11 04:28 UTC, yuu104 commented on oyoyo.txt
ここを直しましょう

2024-07-11 04:29 UTC, yuu104 commented on oyoyo.txt
あああ

2024-07-11 04:33 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
おおお

2024-07-11 04:47 UTC, yuu104 requested changes
直せ

2024-07-11 05:07 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
素晴らしい

2024-07-11 05:10 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
おお

2024-07-11 05:10 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
へー

2024-07-11 05:15 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
リプライ！

2024-07-11 05:18 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
おおリプライ！！

2024-07-11 05:21 UTC, yuu104 reviewed
最後だ！！

2024-07-11 05:21 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
へい7行目！

2024-07-11 05:22 UTC, yuu104 commented on oyoyo.txt
> +oyoyo
最後のリプライだ！！

2024-07-11 06:20 UTC, merged